version: '3.5'

services:
  relay-builder:
    image: s1s5/watchnode
    command: |
      bash -c "
      groupadd -g ${GROUP_ID} app;
      adduser --uid ${USER_ID} app;
      echo 'app:x:1000:1000:app,,,:/home/app:/bin/bash' >> /etc/passwd
      cd /app; watchman; while [ true ]; do gosu app npm run relay -- --watch ; sleep 10; done
      "
    volumes:
      - .:/app

  js-builder:
    image: node
    command: |
      bash -c "
      cd /app; npm run start
      "
    volumes:
      - .:/app
    user: ${USER_ID}:${GROUP_ID}
  
