version: '3.5'

volumes:
  pg_data:
  media_root:

services:
  db:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpass
      - POSTGRES_DB=todo
      - PGDATA=/postgres/data
    volumes:
      - pg_data:/postgres/data
    command: postgres -c max_connections=1000

  app:
    environment:
      - DEBUG=True
      - DATABASE_URL=psql://psqluser:psqlpass@db/todo
      - PYTHONUNBUFFERED=1
      - MEDIA_ROOT=/data/media
    ports:
      - "42100:8000"
    command:  bash -c "sleep 1; if [ ! -f /data/media/.first ]; then sleep 10; touch /data/media/.first; fi; python manage.py migrate --noinput; while [ true ]; do python manage.py runserver 0.0.0.0:8000 ; sleep 10; done"
    volumes:
      - .:/usr/src/app
      - media_root:/data/media
    depends_on:
      - db
