# Generated by Django 3.0.4 on 2020-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architectexample', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
