# Generated by Django 3.0.4 on 2020-04-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architectexample', '0004_auto_20200421_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarynaive',
            options={'ordering': ['-date', '-staff_id']},
        ),
        migrations.AlterModelOptions(
            name='diarywithindex',
            options={'ordering': ['-date', '-staff_id']},
        ),
        migrations.CreateModel(
            name='DiaryPartitionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architectexample.Staff')),
            ],
            options={
                'ordering': ['-date', '-staff_id'],
            },
        ),
        migrations.CreateModel(
            name='DiaryPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architectexample.Staff')),
            ],
            options={
                'ordering': ['-date', '-staff_id'],
            },
        ),
        migrations.AddIndex(
            model_name='diarypartitiondate',
            index=models.Index(fields=['staff'], name='architectex_staff_i_8f53c4_idx'),
        ),
        migrations.AddIndex(
            model_name='diarypartitiondate',
            index=models.Index(fields=['date'], name='architectex_date_1772bc_idx'),
        ),
        migrations.AddIndex(
            model_name='diarypartitiondate',
            index=models.Index(fields=['staff', 'date'], name='architectex_staff_i_7798e9_idx'),
        ),
        migrations.AddIndex(
            model_name='diarypartition',
            index=models.Index(fields=['staff'], name='architectex_staff_i_b8bb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='diarypartition',
            index=models.Index(fields=['date'], name='architectex_date_7639bb_idx'),
        ),
        migrations.AddIndex(
            model_name='diarypartition',
            index=models.Index(fields=['staff', 'date'], name='architectex_staff_i_b17ef6_idx'),
        ),
    ]
