# Generated by Django 3.0.4 on 2020-04-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architectexample', '0005_auto_20200422_1043'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diarypartition',
            name='architectex_staff_i_b8bb7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarypartition',
            name='architectex_date_7639bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarypartition',
            name='architectex_staff_i_b17ef6_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarypartitiondate',
            name='architectex_staff_i_8f53c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarypartitiondate',
            name='architectex_date_1772bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarypartitiondate',
            name='architectex_staff_i_7798e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarywithindex',
            name='architectex_staff_i_cfa764_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarywithindex',
            name='architectex_date_f2d233_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarywithindex',
            name='architectex_staff_i_f2e76a_idx',
        ),
    ]
