# Generated by Django 3.0.4 on 2020-03-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remainder', '0003_todoextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoextra',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='remainder.Todo'),
        ),
    ]
