# Generated by Django 3.0.4 on 2020-03-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainder', '0004_auto_20200324_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(verbose_name='達成したらチェックを入れましょう'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(help_text='やりたいことを明記してください'),
        ),
    ]
